# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19fff700d7d742f4d45c32c3f1f1ce5bd8fa7f3b1aec6f0b6cdeca29ad2daf6a839af1d41247b53964ae0836a45503094a99cd791e11735fdfebb0b19a4ffe7

test:
  secret_key_base: 61e3e19a0c0fcefd775f2fdadcb571db2e3f5c964ae2da325f13aca23839d82cdfe5f42665259a50634d79fb8bc3cea2e66bd762dcebd80069fd5e1cb80352fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
